---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require:
- nokogiri
- open-uri
- playwright-ruby-client
- playwright
- json
- httparty
- date
domains: []
reporters:
# rubocop
- require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
rbs:
  root: sig
  auto_generate: true
