CREATE TABLE T_NOTICIAS(
	id_noticia INT NOT NULL,
	id_fuente INT NOT NULL,
	id_tema INT NOT NULL,
	fecha DATE NOT NULL,
	titulo VARCHAR(50) NOT NULL,
	descripcion_noticia VARCHAR(100),
	CONSTRAINT T_NOTICIAS_PK primary KEY (id_noticia),
	CONSTRAINT T_NOTICIAS_T_FUENTES_FK FOREIGN KEY (id_fuente) REFERENCES tw1project.T_FUENTES(id_fuente),
	CONSTRAINT T_NOTICIAS_T_TEMAS_fk FOREIGN KEY (id_fuente) REFERENCES tw1project.T_TEMAS(id_tema)
);

CREATE TABLE T_DATOS_MONEDAS(
	id_dato INT NOT NULL,
	id_fuente INT NOT NULL,
	id_moneda INT NOT NULL,
	fecha DATE NOT NULL,
	valor_respecto_dolar DECIMAL(15,4) NOT NULL,
	CONSTRAINT T_DATOS_MONEDAS_PK PRIMARY KEY (id_dato),
	CONSTRAINT T_DATOS_MONEDAS_T_FUENTES_FK FOREIGN KEY (id_fuente) REFERENCES tw1project.T_FUENTES (id_fuente),
	CONSTRAINT T_DATOS_MONEDAS_T_MONEDA_FK FOREIGN KEY (id_moneda) REFERENCES tw1project.T_MONEDAS (id_moneda)
);
